# data.py
skills = [
    {"id": 1, "skill": "JavaScript"},
    {"id": 2, "skill": "Python"},
    {"id": 3, "skill": "Java"},
    {"id": 4, "skill": "C#"},
    {"id": 5, "skill": "C++"},
    {"id": 6, "skill": "TypeScript"},
    {"id": 7, "skill": "HTML"},
    {"id": 8, "skill": "CSS"},
    {"id": 9, "skill": "React"},
    {"id": 10, "skill": "Angular"},
    {"id": 11, "skill": "Vue.js"},
    {"id": 12, "skill": "Node.js"},
    {"id": 13, "skill": "Express.js"},
    {"id": 14, "skill": "Django"},
    {"id": 15, "skill": "Flask"},
    {"id": 16, "skill": "Spring Boot"},
    {"id": 17, "skill": "REST APIs"},
    {"id": 18, "skill": "GraphQL"},
    {"id": 19, "skill": "SQL"},
    {"id": 20, "skill": "NoSQL"},
    {"id": 21, "skill": "MongoDB"},
    {"id": 22, "skill": "PostgreSQL"},
    {"id": 23, "skill": "MySQL"},
    {"id": 24, "skill": "Git"},
    {"id": 25, "skill": "GitHub"},
    {"id": 26, "skill": "Docker"},
    {"id": 27, "skill": "Kubernetes"},
    {"id": 28, "skill": "CI/CD"},
    {"id": 29, "skill": "AWS"},
    {"id": 30, "skill": "Azure"},
    {"id": 31, "skill": "GCP"},
    {"id": 32, "skill": "Microservices"},
    {"id": 33, "skill": "Unit Testing"},
    {"id": 34, "skill": "Integration Testing"},
    {"id": 35, "skill": "Agile Methodologies"},
    {"id": 36, "skill": "Scrum"},
    {"id": 37, "skill": "Jira"},
    {"id": 38, "skill": "TDD"},
    {"id": 39, "skill": "BDD"},
    {"id": 40, "skill": "OOP"},
    {"id": 41, "skill": "Functional Programming"},
    {"id": 42, "skill": "Data Structures"},
    {"id": 43, "skill": "Algorithms"},
    {"id": 44, "skill": "Web Security"},
    {"id": 45, "skill": "OAuth"},
    {"id": 46, "skill": "JWT"},
    {"id": 47, "skill": "Performance Optimization"},
    {"id": 48, "skill": "Debugging"},
    {"id": 49, "skill": "Cloud Architecture"},
    {"id": 50, "skill": "Mobile App Development"}
]
